version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 022352218757.dkr.ecr.ap-northeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t Dockerfile
      - docker tag code-build-test:latest 022352218757.dkr.ecr.ap-northeast-1.amazonaws.com/code-build-test:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 022352218757.dkr.ecr.ap-northeast-1.amazonaws.com/code-build-test:latest
